sudo: required
services:
  - docker

before_install:
  - docker build -t tw1118/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true tw1118/docker-react npm run test -- --coverage
# language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-930032333275"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
